---
title: "Manuscript figures and tables"
---

This doc is used to collate source code for the manuscript figures and tables.

```{r}
#| label: setup

# Load required stuff
# -----
source(here::here("0_load-packages-funs.R"))
source(here::here("results", "load-data.R"))

# Plot appearance
# -----

fig_w <- 7.29   # inches
fig_h <- 4.51   # inches
theme_ms <- theme_bw(base_size = 11) +
  theme(
    strip.text.x       = element_text(size = 8),
    axis.title       = element_text(size = 12),
    axis.text        = element_text(size = 10),
    legend.title     = element_text(size = 8),
    legend.text      = element_text(size = 8),
    plot.title       = element_text(size = 16),
    panel.grid.minor = element_blank()
  )
theme_set(theme_ms)

# Palettes
scale_colour_ms <- function(...) scale_colour_viridis_d(option = "G", direction = -1, end = 0.9, ...)
scale_fill_ms   <- function(...) scale_fill_viridis_d(option = "G",   direction = -1, end = 0.9, ...)
colours_lopo <- c("TRUE" = "#2166ac", "FALSE" = "#d73027")
shapes_doses <- c(18, 16, 17, 15, 13)  # diamond, circle, triangle, square, x-circle
```

```{r}
#| label: rerun

# toggles to re-run slow steps
rerun <- FALSE # all
rerun_select_GP <- F # GP selection process
rerun_SBC <- F # simulation-based calibration
if (rerun) source(here::here("3_compute-results.R"))
```

# Main text

```{r}
#| label: fig-england-accuracy

source(here::here("results", "fig-england-accuracy.R"))
fig_england_accuracy
```

```{r}
#| label: tbl-significance-tests
make_row <- function(name, path) {
  p <- readRDS(here::here("results", path))$p |> unname()
  tibble::tibble(
    indicator = name,
    p_value_close = p[1],
    p_value_near = p[2],
    p_value_moderate = p[3]
  )
}

dplyr::bind_rows(
  make_row("Age", "age_test_bootstrap.rds"),
  make_row("Gini", "pt_bootstrap_Gini.rds"),
  make_row("Low Income", "pt_bootstrap_LI.rds"),
  make_row("Vaccine Hesitancy", "pt_bootstrap_VH.rds")
)
```

```{r}
#| label: fig-combined-tests
source(here::here("results", "fig-combined-tests.R"))
fig_combined_tests
```

```{r}
#| label: fig-posterior-draws
source(here::here("results", "fig-posterior-draws.R"))
fig_posterior_Gini_unobs
```

# Supplementary material

```{r}
#| label: fig-lppd-heatmaps
source(here::here("results", "fig-lppd-heatmaps.R"))
fig_heatmaps
```

```{r}
#| label: fig-lppd-lopo
source(here::here("results", "fig-lppd-lopo.R"))
fig_lopo_combined
```

```{r}
#| label: tbl-simulation-recapture
source(here::here("results", "tbl-simulation-recapture.R"))
tbl_sbc_1
tbl_sbc_2
```

```{r}
#| label: fig-provinces-test
source(here::here("results", "fig-provinces-test.R"))
fig_pt_test2
fig_pt_test3
```

```{r}
#| label: posterior-draws-supp
fig_posterior_LI
fig_posterior_VH
fig_posterior_combined
```