# --- Pipeline for the England analysis
# Originally developed in gp-model_england.qmd
# Code generated by Claude Opus 4.6
# Prompting, review of and edits to generated code, additional code annotations by Irena Papst
# Helper functions specifically written to define this pipeline moved to R/pipeline_functions.R

library(targets)
library(crew)

targets::tar_option_set(
  packages = c("dplyr", "ggplot2", "readr", "purrr", "tibble"),
  controller = crew_controller_local(workers = parallel::detectCores()-1)
)

# source all functions in R/
invisible(lapply(list.files(here::here("R"), full.names = TRUE), source))

# --- pipeline ---

list(
  # pipeline settings
  tar_target(n_reps, 40), # number of experimental reps
  tar_target(error_tolerance, 0.05), # tolerable error in the model's vaccine coverage (%) prediction, as a proportion (two-sided)
  tar_target(prov_relation, "UK-Gini"), # province relation metric to use

  # data
  tar_target(file_canada, here::here("data", "measles_vax-coverage-data-cleaned.csv"), format = "file"),
  tar_target(file_england, here::here("data", "ukhsa-chart-download-mmr1-regions.csv"), format = "file"),
  tar_target(data_all, prep_vax_data(file_canada, file_england)),

  # perform experiment over repeated splits of test/train
  tar_target(id_rep, seq_len(n_reps)),
  tar_target(sample_size, get_sample_sizes(data_all)),
  tar_target(
    data_split,
    split_train_test(data_all, sample_size, id_rep),
    pattern = map(id_rep)
  ),
  tar_target( # slow step
    fit_hp,
    fit_hyperparams(
      data_split,
      prov_relation = prov_relation
    ),
    pattern = map(data_split)
  ),
  tar_target(
    accuracy,
    compute_accuracy(
      fit_hp,
      error_tolerance = error_tolerance
    ),
    pattern = map(fit_hp)
  )
)
