# --- Pipeline for the England analysis
# Originally developed in gp-model_england.qmd
# Code generated by Claude Opus 4.6
# Prompting, review of and edits to generated code, additional code annotations by Irena Papst
# Helper functions specifically written to define this pipeline moved to R/pipeline_functions.R

library(targets)

targets::tar_option_set(packages = c("dplyr", "ggplot2", "readr", "purrr", "tibble"))

# source all functions in R/
invisible(lapply(list.files(here::here("R"), full.names = TRUE), source))

# --- pipeline ---

list(
  # pipeline settings
  tar_target(n_reps, 2), # number of experimental reps
  tar_target(error_tolerance, 0.05), # tolerable error in the model's vaccine coverage (%) prediction, as a proportion (two-sided)
  tar_target(prov_relation, "UK-Gini"), # province relation metric to use

  # data
  tar_file(file_canada, here::here("data", "measles_vax-coverage-data-cleaned.csv")),
  tar_file(file_england, here::here("data", "ukhsa-chart-download-mmr1-regions.csv")),
  tar_target(data_all, prep_vax_data(file_canada, file_england)),

  # perform experiment over repeated splits of test/train
  tar_target(rep_id, seq_len(n_reps)),
  tar_target(sample_size, get_sample_sizes(data_all)),
  tar_target(
    data_split,
    split_train_test(data_all, sample_size, rep_id),
    pattern = map(rep_id)
  ),
  tar_target(
    fit,
    fit_and_score(data_split),
    pattern = map(data_split)
  ),
  tar_target(
    accuracy,
    evaluate_accuracy(
      fit,
      prov_relation = prov_relation,
      error_tolerance = error_tolerance
    ),
    pattern = map(fit)
  ),

  # combine all accuracy results
  tar_target(
    accuracy_all,
    bind_rows(accuracy)
  )
)
