---
title: "Gaussian Processes introductory lecture"
output: html_document
date: "2025-04-22"
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
# library(MASS) # For multivariate normal
library(mnormt)
library(dplyr)
library(ggplot2)
library(tidyr)
library(shiny)
library(plotly)
```


```{r}

#mvrnorm(1, c(0,0), matrix(c(2,1,1,2), nrow=2))  # create a multivariate normal distribution (10 draws, mean 0, cov)

x     <- seq(-3, 3, 0.1) 
y     <- seq(-3, 3, 0.1)
mu    <- c(0, 0)
sigma <- matrix(c(2, 1, 1, 2), nrow=2)
f     <- function(x, y) dmnorm(cbind(x, y), mu, sigma)  #dmnorm is pdf of normal
z     <- outer(x, y, f)

expand_grid(x,y) %>% 
  mutate(z=f(x,y)) %>% 
  ggplot() + 
    geom_contour(aes(x=x, y=y, z=z)) + 
    theme_classic() 


#create contour plot
# contour(x, y, z)

```



```{r}

# # UI element: Slider input for standard deviation
# sliderInput("sd",
#             "Standard Deviation:",
#             min = 0.1,
#             max = 5,
#             value = 1,
#             step = 0.1)

# Render the plot based on the slider input
renderPlot({
  sd <- input$sd
  x <- seq(-5*sd, 5*sd, length.out = 1000)
  y <- dnorm(x, mean = 0, sd = sd)
  
  ggplot(data.frame(x, y), aes(x, y)) +
    geom_line(color = "steelblue", size = 1.2) +
    scale_x_continuous(limits=c(-10,10)) + 
    labs(title = paste("Normal Distribution (mean = 0, sd =", sd, ")"),
         x = "x", y = "Density") +
    theme_minimal(base_size = 14)
})


```


```{r}

ksqexp <- function(r, l){  # example covariance function (squared exp)
  out <- exp(-r^2 / (2*l^2))
  return(out)
}

klin <- function(x1, x2, sigma_int, sigma_slope){  # linear covariance function
  out <- sigma_int^2 + sigma_slope^2 * (x1*x2)
  return(out)
}

tibble(r=seq(from=0, to=10, length.out=200)) %>%  #data frame recording value of the example covariance function for a range of lengthscales l
  mutate(`l=1`=ksqexp(r,1)) %>% 
  mutate(`l=2`=ksqexp(r,2)) %>% 
  mutate(`l=5`=ksqexp(r,5)) %>% 
  pivot_longer(-r) %>% 
  ggplot(aes(x=r, y=value, col=name)) +  # plot the example cov function
    geom_line(linewidth=1) + 
    theme_classic() + 
    scale_color_manual(values=c("black","red","blue")) + 
  labs(title="The squared exponential covariance function", col="Length scale", x="Distance between points (r)", y="Covariance")

```


```{r}

kexp <- function(r, l){  # exponential covariance function
  out <- exp(-r / l)
  return(out)
}

tibble(r=seq(from=0, to=10, length.out=200)) %>% 
  mutate(`l=1`=kexp(r,1)) %>% 
  mutate(`l=2`=kexp(r,2)) %>% 
  mutate(`l=5`=kexp(r,5)) %>% 
  pivot_longer(-r) %>% 
  ggplot(aes(x=r, y=value, col=name)) + 
    geom_line(linewidth=1) + 
    theme_classic() + 
    scale_color_manual(values=c("black","red","blue")) + 
  labs(title="The exponential covariance function", col="Length scale", x="Distance between points", y="Covariance")

```


```{r}

npts <- 101
# npts <- 5
l <- 1
xvals <- seq(from=0, to=10, length.out=npts)
covmat <- expand_grid(x1=xvals,x2=xvals) %>% 
  mutate(k=ksqexp(abs(x1-x2), l)) %>%
  # mutate(k=kexp(abs(x1-x2), l)) %>%
  # mutate(k=klin(x1, x2, 1, 1)) %>%
  pull(k) %>% 
  matrix(nrow=npts)

gpdraw_df <- tibble()
for(indexA in 1:50){
# for(indexA in 1:1){
  gpdraw_df <- bind_rows(gpdraw_df, tibble(
    draw=indexA, x=xvals, y=rmnorm(1, rep(0,npts), covmat + 1e-6*diag(npts))
  ))
  # gpdraw <- rmnorm(1, rep(0,npts), covmat)  
}


gpdraw_df %>% 
    ggplot(aes(x=x, y=y, group=factor(draw))) + 
      geom_point(size=1, alpha=0.3) +
      geom_line(size=0.5, alpha=0.3) +
      theme_classic() + 
    scale_y_continuous(limits=c(-5,5))

gpdraw_df_kept <- gpdraw_df %>% 
  mutate(keep=case_when(x==2.5 & (y>0.9 & y<1.1)~1, TRUE~0)) %>% 
  group_by(draw) %>% 
  mutate(keep=max(keep)) %>% 
  filter(keep==1)

gpdraw_df %>% 
    ggplot() + 
      geom_point(aes(x=x, y=y, group=factor(draw)), size=1, alpha=0.3) +
      geom_line(aes(x=x, y=y, group=factor(draw)), size=0.5, alpha=0.3) +
      geom_point(data=gpdraw_df_kept, aes(x=x, y=y, group=factor(draw)), col="blue") + 
      geom_line(data=gpdraw_df_kept, aes(x=x, y=y, group=factor(draw)), col="blue") + 
      geom_point(data=tibble(x=2.5, y=1), aes(x=x, y=y), size=2, col="red") + 
      theme_classic() + 
    scale_y_continuous(limits=c(-5,5))

# round(covmat,4)
```




```{r}

# "Test" (prediction) points
npts <- 101
l <- 1
measnoise <- 1e-4
xstar <- seq(from=0, to=10, length.out=npts)

# "Training" (data) points
x <- c(2, 4, 6, 8)
y <- rnorm(length(x), 0, 1)

# Define a function to generate squared-exponential covariance matrices
kgen <- function(x1, x2, l){
  out <- expand_grid(x1=x1, x2=x2) %>% 
    mutate(k=ksqexp(abs(x1-x2),l)) %>%
    # mutate(k=kexp(abs(x1-x2),l)) %>%
    pull(k) %>% 
    matrix(nrow=length(x1), byrow=TRUE)
}

covmat <- kgen(xstar, xstar, 1)

ksb <- kgen(xstar, x, l)  # relationship between unobserved x* and observed x
kbs <- kgen(x, xstar, l)  # relationship between observed x and unobserved x*
kbb <- kgen(x,x, l) + measnoise*diag(length(x))
kss <- kgen(xstar, xstar, l) 

mvnmeanpost <- ksb%*%solve(kbb)%*%y  # calculating mean of the posterior
covmatpost <- kss - ksb%*%solve(kbb)%*%kbs  # calcuating cov matrix of the posterior
# plot(xstar, mvnmeanpost)
# points(x,y, pch=2)

gpdraw_df <- tibble()
for(indexA in 1:50){  # then take 50 draws from the posterior
  gpdraw_df <- bind_rows(gpdraw_df, tibble(
    draw=indexA, 
    x=xstar, 
    y=rmnorm(1, mvnmeanpost, covmatpost + 1e-6*diag(nrow(covmatpost)))
  ))
}

gpdraw_df %>%  # plot the 50 draws of the posterior
    ggplot() + 
      geom_point(aes(x=x, y=y, group=factor(draw)), size=1, alpha=0.3) +
      geom_line(aes(x=x, y=y, group=factor(draw)), size=0.5, alpha=0.3) +
      geom_point(data=tibble(x=x, y=y), aes(x=x,y=y), size=4, col="blue") +
      theme_classic() + 
    scale_y_continuous(limits=c(-5,5))

```


```{r}
# new example in 2d -- prior
npts <- 40
l <- 1
xvals <- seq(from=0, to=10, length.out=npts)
yvals <- seq(from=0, to=10, length.out=npts)
covmat <- expand_grid(x1=xvals, y1=yvals, x2=xvals, y2=yvals) %>% 
  mutate(k=ksqexp(sqrt((x1-x2)^2 + (y1-y2)^2), l)) %>%
  # mutate(k=kexp(sqrt((x1-x2)^2 + (y1-y2)^2), l)) %>%
  pull(k) %>% 
  matrix(nrow=npts^2)

xydf <- expand_grid(x=xvals, y=yvals)

gpdraw_df <- tibble()  # plot of a single realisation from a 2D gaussian process, with both axes independent variables (model paramters) - one draw from the prior (we would add data points then 'update' for posterior)
for(indexA in 1:1){
  gpdraw_df <- bind_rows(gpdraw_df, tibble(
    draw=indexA, x=xydf$x, y=xydf$y, z=rmnorm(1, rep(0,npts^2), covmat + 1e-6*diag(npts^2))
  ))
  
}
 
gpdraw_df %>%
    ggplot(aes(x=x, y=y, z=z, group=factor(draw))) +
      geom_contour() + 
      theme_classic()

z_matrix <- matrix(gpdraw_df$z, nrow = npts, ncol = npts, byrow = FALSE)  # same plot as above
plot_ly(x = xvals, y = yvals, z = z_matrix, type = "surface")

```
