---
title: "Manuscript figures and tables"
---

This doc is used to source figures and tables for the [manuscript](https://docs.google.com/document/d/1CMSp4e_r6As2yim0dHeWNWYWK2msEPtZZl-3ekjgz0I/edit?tab=t.0). File names follow a convention of starting with `fig-` or `tbl-`, then the cross-reference label used in the manuscript draft.

```{r}
#| label: setup
source(here::here("results", "setup.R"))
```

```{r}
#| label: rerun
rerun <- FALSE
rerun_select_GP <- F
rerun_SBC <- F
if (rerun) source(here::here("results", "results_setup.R"))
```

## Main figures

```{r}
#| label: fig-data-plot
source(here::here("results", "fig-data-plot.R"))
fig_data_plot
```

```{r}
#| label: fig-england
# placeholder for model fits to full england data (results/fig-england.R)
# do we want this in the supp instead...?
```

```{r}
#| label: fig-england-accuracy
#| eval: false
#| need to run the targets pipeline first to get the results... this will take ~1 hr on a basic laptop as it involves 40 hyperparameter selection processes!
#| targets::tar_make(accuracy)
source(here::here("results", "fig-england-accuracy.R"))
fig_england_accuracy
```

```{r}
#| label: fig-posterior-draws
source(here::here("results", "fig-posterior-draws.R"))
fig_posterior_Gini
fig_posterior_LI
fig_posterior_VH
fig_posterior_combined
fig_posterior_Gini_unobs
```

## Supplementary figures

```{r}
#| label: fig-lppd-lopo
source(here::here("results", "fig-lppd-lopo.R"))
fig_lopo_combined
```

```{r}
#| label: fig-provinces-test
source(here::here("results", "fig-provinces-test.R"))  # *we plan to replace this plot with a plot equiv to the ages test!
fig_provinces_test  # values for AR and NR currently missing
```

```{r}
#| label: fig-lppd-heatmaps
source(here::here("results", "fig-lppd-heatmaps.R"))
fig_heatmaps
```

```{r}
#| label: fig-ages-test
source(here::here("results", "fig-ages-test.R"))
fig_ages_test1
fig_ages_test2
```

```{r}
#| label: fig-england  
#| eval: FALSE
source(here::here("results", "fig-england.R"))  # Irena to add England figs here
fig_england_posterior_Gini
fig_england_posterior_LI
fig_england_heatmap_Gini
fig_england_heatmap_LI
```

## Tables

```{r}
#| label: tbl-simulation-recapture
source(here::here("results", "tbl-simulation-recapture.R"))
tbl_sbc
```
